"""Initial schema

Revision ID: 95ce5599f3d5
Revises: 
Create Date: 2026-05-10 12:56:06.375039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95ce5599f3d5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('normalized_value', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'normalized_value', name='uq_tags_kind_norm')
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index('ix_tags_normalized_value', ['normalized_value'], unique=False)

    op.create_table('tracks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('spotify_id', sa.String(length=64), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_name', sa.String(length=512), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('artist', sa.String(length=512), nullable=True),
    sa.Column('album', sa.String(length=512), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tracks_file_hash'), ['file_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_tracks_spotify_id'), ['spotify_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_tracks_state'), ['state'], unique=False)

    op.create_table('beats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('position_ms', sa.Integer(), nullable=False),
    sa.Column('beat_number', sa.Integer(), nullable=True),
    sa.Column('bar_number', sa.Integer(), nullable=True),
    sa.Column('downbeat', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('beats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_beats_track_id'), ['track_id'], unique=False)

    op.create_table('phrases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('start_ms', sa.Integer(), nullable=False),
    sa.Column('end_ms', sa.Integer(), nullable=False),
    sa.Column('bar_count', sa.Integer(), nullable=True),
    sa.Column('phrase_type', sa.String(length=32), nullable=True),
    sa.Column('energy_level', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('phrases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_phrases_track_id'), ['track_id'], unique=False)

    op.create_table('session_plays',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('played_at', sa.DateTime(), nullable=False),
    sa.Column('position_in_set', sa.Integer(), nullable=False),
    sa.Column('energy_at_play', sa.Integer(), nullable=True),
    sa.Column('transition_type', sa.String(length=16), nullable=True),
    sa.Column('duration_played_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session_plays', schema=None) as batch_op:
        batch_op.create_index('ix_session_plays_session_position', ['session_id', 'position_in_set'], unique=False)
        batch_op.create_index('ix_session_plays_track_played', ['track_id', 'played_at'], unique=False)

    op.create_table('stem_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('model_used', sa.String(length=64), nullable=True),
    sa.Column('separation_quality', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('track_id', 'kind', name='uq_stem_files_track_kind')
    )
    with op.batch_alter_table('stem_files', schema=None) as batch_op:
        batch_op.create_index('ix_stem_files_track_id', ['track_id'], unique=False)

    op.create_table('track_edges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_track_id', sa.Integer(), nullable=False),
    sa.Column('to_track_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('meta', sa.Text(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('from_track_id != to_track_id', name='ck_track_edges_no_self_loop'),
    sa.ForeignKeyConstraint(['from_track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_track_id', 'to_track_id', 'kind', name='uq_track_edges_from_to_kind')
    )
    with op.batch_alter_table('track_edges', schema=None) as batch_op:
        batch_op.create_index('ix_track_edges_from_kind_weight', ['from_track_id', 'kind', 'weight'], unique=False)
        batch_op.create_index('ix_track_edges_to_kind_weight', ['to_track_id', 'kind', 'weight'], unique=False)

    op.create_table('track_tags',
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('track_id', 'tag_id', 'source')
    )
    with op.batch_alter_table('track_tags', schema=None) as batch_op:
        batch_op.create_index('ix_track_tags_tag_id', ['tag_id'], unique=False)

    op.create_table('audio_analysis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('stem_file_id', sa.Integer(), nullable=True),
    sa.Column('bpm', sa.Float(), nullable=True),
    sa.Column('bpm_confidence', sa.Float(), nullable=True),
    sa.Column('key_camelot', sa.String(length=4), nullable=True),
    sa.Column('key_standard', sa.String(length=8), nullable=True),
    sa.Column('key_confidence', sa.Float(), nullable=True),
    sa.Column('energy_overall', sa.Float(), nullable=True),
    sa.Column('energy_peak', sa.Float(), nullable=True),
    sa.Column('floor_energy', sa.Integer(), nullable=True),
    sa.Column('brightness', sa.Float(), nullable=True),
    sa.Column('warmth', sa.Float(), nullable=True),
    sa.Column('danceability', sa.Float(), nullable=True),
    sa.Column('presence_ratio', sa.Float(), nullable=True),
    sa.Column('rms_curve', sa.LargeBinary(), nullable=True),
    sa.Column('rms_curve_hop_ms', sa.Integer(), nullable=True),
    sa.Column('rms_curve_length', sa.Integer(), nullable=True),
    sa.Column('presence_intervals', sa.Text(), nullable=True),
    sa.Column('dominant_pitch_camelot', sa.String(length=4), nullable=True),
    sa.Column('dominant_pitch_confidence', sa.Float(), nullable=True),
    sa.Column('vocal_present', sa.Boolean(), nullable=True),
    sa.Column('kick_density', sa.Float(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['stem_file_id'], ['stem_files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audio_analysis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audio_analysis_key_camelot'), ['key_camelot'], unique=False)

    # Partial unique indexes for audio_analysis. SQLite treats NULL as
    # distinct in plain UNIQUE constraints, so we need partial indexes to
    # enforce "one full-mix analysis per track" and "one analysis per stem".
    # Alembic autogen cannot emit these — they're added by hand.
    op.execute(
        "CREATE UNIQUE INDEX uq_audio_analysis_track_fullmix "
        "ON audio_analysis(track_id) WHERE stem_file_id IS NULL"
    )
    op.execute(
        "CREATE UNIQUE INDEX uq_audio_analysis_stem "
        "ON audio_analysis(stem_file_id) WHERE stem_file_id IS NOT NULL"
    )

    op.create_table('regions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('stem_file_id', sa.Integer(), nullable=True),
    sa.Column('position_ms', sa.Integer(), nullable=False),
    sa.Column('length_ms', sa.Integer(), nullable=True),
    sa.Column('region_type', sa.String(length=16), nullable=False),
    sa.Column('section_label', sa.String(length=16), nullable=True),
    sa.Column('bar_count', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('color', sa.String(length=8), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('snapped_to', sa.String(length=8), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['stem_file_id'], ['stem_files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('regions', schema=None) as batch_op:
        batch_op.create_index('ix_regions_stem_file_id_region_type', ['stem_file_id', 'region_type'], unique=False, sqlite_where=sa.text('stem_file_id IS NOT NULL'))
        batch_op.create_index('ix_regions_track_id_region_type', ['track_id', 'region_type'], unique=False)

    op.create_table('track_embeddings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('stem_file_id', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=True),
    sa.Column('dim', sa.Integer(), nullable=False),
    sa.Column('embedding', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['stem_file_id'], ['stem_files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('track_id', 'stem_file_id', 'model', 'model_version', name='uq_track_embeddings_track_stem_model_version')
    )
    with op.batch_alter_table('track_embeddings', schema=None) as batch_op:
        batch_op.create_index('ix_track_embeddings_model', ['model'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track_embeddings', schema=None) as batch_op:
        batch_op.drop_index('ix_track_embeddings_model')

    op.drop_table('track_embeddings')
    with op.batch_alter_table('regions', schema=None) as batch_op:
        batch_op.drop_index('ix_regions_track_id_region_type')
        batch_op.drop_index('ix_regions_stem_file_id_region_type', sqlite_where=sa.text('stem_file_id IS NOT NULL'))

    op.drop_table('regions')
    with op.batch_alter_table('audio_analysis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audio_analysis_key_camelot'))

    op.drop_table('audio_analysis')
    with op.batch_alter_table('track_tags', schema=None) as batch_op:
        batch_op.drop_index('ix_track_tags_tag_id')

    op.drop_table('track_tags')
    with op.batch_alter_table('track_edges', schema=None) as batch_op:
        batch_op.drop_index('ix_track_edges_to_kind_weight')
        batch_op.drop_index('ix_track_edges_from_kind_weight')

    op.drop_table('track_edges')
    with op.batch_alter_table('stem_files', schema=None) as batch_op:
        batch_op.drop_index('ix_stem_files_track_id')

    op.drop_table('stem_files')
    with op.batch_alter_table('session_plays', schema=None) as batch_op:
        batch_op.drop_index('ix_session_plays_track_played')
        batch_op.drop_index('ix_session_plays_session_position')

    op.drop_table('session_plays')
    with op.batch_alter_table('phrases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_phrases_track_id'))

    op.drop_table('phrases')
    with op.batch_alter_table('beats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_beats_track_id'))

    op.drop_table('beats')
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tracks_state'))
        batch_op.drop_index(batch_op.f('ix_tracks_spotify_id'))
        batch_op.drop_index(batch_op.f('ix_tracks_file_hash'))

    op.drop_table('tracks')
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index('ix_tags_normalized_value')

    op.drop_table('tags')
    op.drop_table('sessions')
    # ### end Alembic commands ###
